### ISSUE TITLE
补充实现manage 执行器通过createTransaction rpc 接口去创建 tx

### ISSUE THREAD

**Issue by harrylee2015** [33cn/chain33#159]
manage目前没有实现通过createTransaction rpc接口去创建tx, 需要支持这一操作

**Comment by 33cn** [comment]
这个是不是默认自动支持的

**Comment by harrylee2015** [comment]
@33cn  有这个接口，mange没有具体实现

**Comment by 33cn** [comment]
你可以看一下 ExecutorType 中 CreateTx 的实现，基础类里面已经做了处理

**Comment by 33cn** [comment]
```
//CreateTx 构造tx交易重构完成后删除
func (base *ExecTypeBase) CreateTx(action string, msg json.RawMessage) (*Transaction, error) {
	data, err := base.GetAction(action)
	if err != nil {
		return nil, err
	}
	b, err := msg.MarshalJSON()
	if err != nil {
		tlog.Error(action + " MarshalJSON  error")
		return nil, err
	}
	err = JSONToPB(b, data)
	if err != nil {
		tlog.Error(action + " jsontopb  error")
		return nil, err
	}
	return base.CreateTransaction(action, data)
}

//CreateTransaction 构造Transaction
func (base *ExecTypeBase) CreateTransaction(action string, data Message) (tx *Transaction, err error) {
	defer func() {
		if e := recover(); e != nil {
			err = ErrActionNotSupport
		}
	}()
	value := base.child.GetPayload()
	v := reflect.New(base.actionListValueType["Value_"+action])
	vn := reflect.Indirect(v)
	if vn.Kind() != reflect.Struct {
		tlog.Error("CreateTransaction vn not struct kind", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field := vn.FieldByName(action)
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction vn filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field.Set(reflect.ValueOf(data))
	value2 := reflect.Indirect(reflect.ValueOf(value))
	if value2.Kind() != reflect.Struct {
		tlog.Error("CreateTransaction value2 not struct kind", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field = value2.FieldByName("Value")
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction value filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field.Set(v)

	field = value2.FieldByName("Ty")
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction ty filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	tymap := base.child.GetTypeMap()
	if tyid, ok := tymap[action]; ok {
		field.Set(reflect.ValueOf(tyid))
		return &Transaction{Payload: Encode(value)}, nil
	}
	return nil, ErrActionNotSupport
}
```

**Comment by 33cn** [comment]
这个部分应该是可以对一般对交易都是可以构造对。除非 CreateTx 被子类重写了

**Comment by 33cn** [comment]
我待会写一个单元测试，演示一下如何创建。

**Comment by harrylee2015** [comment]
manage 重写了createTx方法
```go
// CreateTx create a tx
// TODO not going to change the implementation, complete the reconfiguration of the structure first
func (m ManageType) CreateTx(action string, message json.RawMessage) (*types.Transaction, error) {
	var tx *types.Transaction
	return tx, nil
}
```
这里应该要删掉才会调到基类的createTx

**Comment by 33cn** [comment]
你把manage 里面的 cerateTx 删除，再加一个创建的测试

**Comment by harrylee2015** [comment]
我测试了一下，基类的createTx 方法好像有问题，type.Encode时传入的时nil,看了一下代码，value好像确实是没有赋值
```go
// GetPayload return manageaction
func (m *ManageType) GetPayload() types.Message {
	return &ManageAction{}
}
```

```go
//CreateTransaction 构造Transaction
func (base *ExecTypeBase) CreateTransaction(action string, data Message) (tx *Transaction, err error) {
	defer func() {
		if e := recover(); e != nil {
			err = ErrActionNotSupport
		}
	}()
	value := base.child.GetPayload()
	v := reflect.New(base.actionListValueType["Value_"+action])
	vn := reflect.Indirect(v)
	if vn.Kind() != reflect.Struct {
		tlog.Error("CreateTransaction vn not struct kind", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field := vn.FieldByName(action)
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction vn filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field.Set(reflect.ValueOf(data))
	value2 := reflect.Indirect(reflect.ValueOf(value))
	if value2.Kind() != reflect.Struct {
		tlog.Error("CreateTransaction value2 not struct kind", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field = value2.FieldByName("Value")
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction value filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	field.Set(v)

	field = value2.FieldByName("Ty")
	if !field.IsValid() || !field.CanSet() {
		tlog.Error("CreateTransaction ty filed can't set", "exectutor", base.child.GetName(), "action", action)
		return nil, ErrActionNotSupport
	}
	tymap := base.child.GetTypeMap()
	if tyid, ok := tymap[action]; ok {
		field.Set(reflect.ValueOf(tyid))

                *** 这里value是空值***
		return &Transaction{Payload: Encode(value)}, nil
	}
	return nil, ErrActionNotSupport
}
```

我测试方式：
``` bash
	   curl --data-binary '{"jsonrpc":"2.0", "id": 1, "method":"Chain33.CreateTransaction","params":[{"execer":"manage", "actionName":"Modify", "payload":{"ty": 0,"value":{"key":"token-finisher","value":"16ReZHzMCGtPt8B7XbnZQ2jeXsPG9wEufh","op":"add","addr":""}}}]} ' \
        -H 'content-type:text/plain;' \
        http://localhost:8801
```


panic 错误，是由nil 调用 type.Encode() 引起的

```bash
2018-12-05 16:32:23.310871 I | http: panic serving 127.0.0.1:36304: proto: Marshal called with nil
goroutine 2548 [running]:
net/http.(*conn).serve.func1(0xc425372000)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x12b1000, 0xc4200424b0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/33cn/plugin/vendor/github.com/33cn/chain33/types.Encode(0x1f4d060, 0x0, 0x6, 0xc4240980e0, 0x6c)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/types/types.go:193 +0x83
github.com/33cn/plugin/vendor/github.com/33cn/chain33/rpc.(*Chain33).CreateTransaction(0xc4204528e0, 0xc42a3c8280, 0xc4261ebb40, 0x0, 0x0)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/rpc/jrpchandler.go:1160 +0x21c
reflect.Value.call(0xc422f3da40, 0xc422f2c5f0, 0x13, 0x1496c19, 0x4, 0xc422c93970, 0x3, 0x3, 0x12a8080, 0x14, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc422f3da40, 0xc422f2c5f0, 0x13, 0xc422c93970, 0x3, 0x3, 0x16, 0x16, 0x16)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420501a40, 0xc420505c20, 0xc42f174a50, 0xc422f41700, 0xc42b27fb00, 0x1213c80, 0xc42a3c8280, 0x16, 0x121e5c0, 0xc4261ebb40, ...)
	/usr/local/go/src/net/rpc/server.go:381 +0x142
net/rpc.(*Server).ServeRequest(0xc420505c20, 0x1f51720, 0xc422c8a0c0, 0x4, 0x0)
	/usr/local/go/src/net/rpc/server.go:496 +0x22c
github.com/33cn/plugin/vendor/github.com/33cn/chain33/rpc.(*JSONRPCServer).Listen.func1(0x1f4f820, 0xc422ce4000, 0xc420529200)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/rpc/http.go:103 +0x8da
net/http.HandlerFunc.ServeHTTP(0xc42043a9f0, 0x1f4f820, 0xc422ce4000, 0xc420529200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/33cn/plugin/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1f4f820, 0xc422ce4000, 0xc420529200)
	/home/harry/gopath/src/github.com/33cn/plugin/vendor/github.com/rs/cors/cors.go:207 +0x108
net/http.HandlerFunc.ServeHTTP(0xc420289c40, 0x1f4f820, 0xc422ce4000, 0xc420529200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc4204f2dd0, 0x1f4f820, 0xc422ce4000, 0xc420529200)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc425372000, 0x1f50ba0, 0xc42a3c8000)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

```

**Comment by 33cn** [comment]
{"key":"token-finisher","value":"16ReZHzMCGtPt8B7XbnZQ2jeXsPG9wEufh","op":"add","addr":""}

**Comment by 33cn** [comment]
直接填写这个测试一下

**Comment by 33cn** [comment]
panic 的问题要修复一下，判断一下数据传入不对的情况下，为nil的情况。

**Comment by harrylee2015** [comment]
还好，代码里面有recover操作，系统不会奔溃
