### ISSUE TITLE
store 模块 空指针的bug

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#361]
程序正常运行时，出现如下panic 日志信息
panic: interface conversion: interface {} is nil, not *mavl.Tree

goroutine 11623612 [running]:
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store/mavl.(*Store).Get(0xa4e8200, 0xac99cb0, 0xac99cb0, 0x0, 0x0)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store/mavl/mavl.go:92 +0x3bc
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store.(*BaseStore).processMessage.func2(0x8a97bce, 0x5, 0x17, 0x0, 0x15e507a, 0x0, 0x8a3e5e0, 0xac99cb0, 0x15573d00, 0xb27b6a0, ...)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store/base.go:105 +0x86
created by github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store.(*BaseStore).processMessage
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/store/base.go:103 +0x24c

**Comment by libangzhu** [comment]
![_20190221213237](https://user-images.githubusercontent.com/16385190/53172437-4f5f2680-3620-11e9-8a2c-bc0aace5dda8.png)
